### ISSUE TITLE
Show first five members of Athletes Dataset

### ISSUE THREAD

**Issue by ankurg132** [gdscrgpv/2021-Olympics-Data-Analysis#1]
We need to have a Jupyter Notebook file named as athletes-analysis.ipynb which should show the first five data of Athletes dataset by importing the data from the excel file.

**Comment by sabicd** [comment]
Hey @ankurg132 i would like to pick this one up
[PR for the notebook](https://github.com/gdscrgpv/2021-Olympics-Data-Analysis/pull/9)

**Comment by chidam333** [comment]
hi bro please assign this to me

**Comment by ankurg132** [comment]
Solved by @sabicd's Pull request.
