### ISSUE TITLE
Show first five data of entries gender

### ISSUE THREAD

**Issue by ankurg132** [gdscrgpv/2021-Olympics-Data-Analysis#5]
We need to have a Jupyter Notebook file named as entries-gender-analysis.ipynb which should show the first five data of Entries Gender dataset by importing the data from the excel file.

**Comment by arrowarchit** [comment]
Hi @ankurg132 can you please assign this task to me?

**Comment by ankurg132** [comment]
Sure

**Comment by arrowarchit** [comment]
@ankurg132 Hey, I have added a pull request, please review.

**Comment by ankurg132** [comment]
Looks good, merged the PR and we can now close this issue. You can go for more analysis on the same notebook if interested.
